# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 07:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20160525_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='repo',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='repo',
            name='webhook_url',
        ),
        migrations.AddField(
            model_name='repo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 26, 7, 27, 9, 880720, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repo',
            name='webhook_id',
            field=models.TextField(default='-1'),
            preserve_default=False,
        ),
    ]
