# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20160526_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='result',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='repo',
            name='webhook_id',
            field=models.IntegerField(),
        ),
    ]
